image:
- Visual Studio 2022
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: qVxHdHEOZuIp/koD1XaNnRE+rzVye8zPvTNYKwIBBI4gn9m9p92esysQOxdiskAfnJn7GYQUHTouvlSoaWIblxOxaEX8o+p4OUZ4Os+4Nbzne8O9L/Rw02c+Y2JnbRYh

install:
- pip install -r requirements.txt

build_script:
- flet pack py_ratios.py --name py-ratios --icon icon.png --product-name py-ratios --product-version "1.0.0" --copyright "Copyright (c) 2023 YourCompany Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: false

#
#   Windows package
# 
for:
-

  matrix:
    only:
    - image: Visual Studio 2022

  after_build:
  - 7z a py-ratios-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: py-ratios-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf py-ratios-macos.tar.gz -C dist counter.app

  artifacts:
  - path: pyratios-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf py-ratios-linux.tar.gz -C dist counter

  artifacts:
  - path: py-ratios-linux.tar.gz